<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>JieXiPreserveData.Tests</AssemblyName>
    <RootNamespace>JieXiInstaller.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\installerHelper\JieXiPreserveData.csproj" />
  </ItemGroup>
</Project>
