import java.util.Properties

plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)

    alias(libs.plugins.ksp)
}

val releaseProperties = Properties().apply {
    val config = file("D:/CodexSecrets/解析/release.properties")
    if (config.isFile) config.reader(Charsets.UTF_8).use(::load)
}
fun buildConfigString(value: String) = "\"${value.replace("\\", "\\\\").replace("\"", "\\\"")}\""

android {
    namespace = "com.yunx.app"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.yunx.app"
        minSdk = 24
        targetSdk = 36
        versionCode = 41
        versionName = "4.1.0"

        buildConfigField("String", "UPDATE_MANIFEST_URL", buildConfigString(releaseProperties.getProperty("updateManifestUrl", "")))
        buildConfigField("String", "UPDATE_PUBLIC_KEY", buildConfigString(releaseProperties.getProperty("updatePublicKeyBase64", "")))
        buildConfigField("String", "GITHUB_REPOSITORY_URL", buildConfigString(releaseProperties.getProperty("githubFeedbackUrl", "")))

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        if (releaseProperties.isNotEmpty()) {
            create("release") {
                storeFile = file(releaseProperties.getProperty("storeFile"))
                storePassword = releaseProperties.getProperty("storePassword")
                keyAlias = releaseProperties.getProperty("keyAlias")
                keyPassword = releaseProperties.getProperty("keyPassword")
                enableV2Signing = true
                enableV3Signing = true
            }
        }
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.findByName("release")
        }
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    packaging {
        jniLibs {
            // youtube-dl-android opens libpython.zip.so/libffmpeg.zip.so from
            // nativeLibraryDir during initialization. They must therefore be
            // extracted on install instead of loaded directly from the APK.
            useLegacyPackaging = true
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }
}

dependencies {
    implementation(project(":sharedCore"))
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation(libs.room.runtime)
    implementation(libs.room.ktx)          // 提供协程扩展，如 Flow、suspend
    ksp(libs.room.compiler)

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    implementation("io.github.junkfood02.youtubedl-android:library:0.18.1")
    implementation("io.github.junkfood02.youtubedl-android:ffmpeg:0.18.1")
    implementation("io.github.junkfood02.youtubedl-android:aria2c:0.18.1")
    implementation("com.google.code.gson:gson:2.13.2")
    implementation("io.coil-kt:coil-compose:2.7.0")
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.json:json:20250107")
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)
}

// Windows CI/desktop hosts can otherwise fork one JVM per CPU and intermittently
// lose the Gradle worker pipe. A single test JVM is faster for this small suite
// and, more importantly, makes the release gate deterministic.
tasks.withType<org.gradle.api.tasks.testing.Test>().configureEach {
    maxParallelForks = 1
}

// 1.2.7 and earlier test releases used the original Android key. Public 4.0
// APKs use the private release key as the current signer on every supported
// Android version. The optional v3/v3.1-only migration APK embeds the old ->
// release lineage so Android 13+ legacy test installs can upgrade in place.
// Android 12L and earlier test installs must be removed once before installing
// the public build. The migration APK is not a general-distribution artifact.
// Neither private key nor the proof-of-rotation lineage is stored in Git.
val legacyAndroidKey = file("D:/CodexSecrets/解析/android-legacy-1.2.7.jks")
val androidSigningLineage = file("D:/CodexSecrets/解析/android-signing-lineage.bin")
val androidReleaseOutputDirectory = file("D:/CodexBuilds/JieXi/${android.defaultConfig.versionName}/android")
val androidReleaseOutput = androidReleaseOutputDirectory.resolve("解析-Android-${android.defaultConfig.versionName}.apk")
val androidLegacyUpgradeOutput = androidReleaseOutputDirectory.resolve(
    "解析-Android-${android.defaultConfig.versionName}-legacy-api33-upgrade.apk"
)
val apksignerExecutable = android.sdkDirectory.resolve("build-tools/${android.buildToolsVersion}/apksigner.bat")
val assembledAndroidRelease = layout.buildDirectory.file("outputs/apk/release/app-release.apk")

val prepareAndroidSigningLineage by tasks.registering(Exec::class) {
    group = "distribution"
    description = "Create the private Android signing-key rotation lineage."
    inputs.file(legacyAndroidKey)
    inputs.file(file(releaseProperties.getProperty("storeFile", "D:/missing-release-key.jks")))
    outputs.file(androidSigningLineage)
    environment("JIEXI_OLD_STORE_PASS", "android")
    environment("JIEXI_OLD_KEY_PASS", "android")
    environment("JIEXI_NEW_STORE_PASS", releaseProperties.getProperty("storePassword", ""))
    environment("JIEXI_NEW_KEY_PASS", releaseProperties.getProperty("keyPassword", ""))
    doFirst {
        check(releaseProperties.isNotEmpty()) { "D:/CodexSecrets/解析/release.properties is required." }
        check(apksignerExecutable.isFile) { "apksigner not found: $apksignerExecutable" }
        check(legacyAndroidKey.isFile) { "Legacy Android update key is missing: $legacyAndroidKey" }
        check(file(releaseProperties.getProperty("storeFile")).isFile) { "Android release key is missing." }
        androidSigningLineage.parentFile.mkdirs()
        if (androidSigningLineage.exists()) check(androidSigningLineage.delete()) {
            "Unable to refresh Android signing lineage: $androidSigningLineage"
        }
    }
    commandLine(
        apksignerExecutable.absolutePath,
        "rotate",
        "--out", androidSigningLineage.absolutePath,
        "--old-signer",
        "--ks", legacyAndroidKey.absolutePath,
        "--ks-key-alias", "androiddebugkey",
        "--ks-pass", "env:JIEXI_OLD_STORE_PASS",
        "--key-pass", "env:JIEXI_OLD_KEY_PASS",
        "--new-signer",
        "--ks", releaseProperties.getProperty("storeFile", ""),
        "--ks-key-alias", releaseProperties.getProperty("keyAlias", ""),
        "--ks-pass", "env:JIEXI_NEW_STORE_PASS",
        "--key-pass", "env:JIEXI_NEW_KEY_PASS"
    )
}

val packageAndroidLegacyUpgrade by tasks.registering(Exec::class) {
    dependsOn(tasks.named("assembleRelease"), prepareAndroidSigningLineage)
    group = "distribution"
    description = "Create release-key v3/v3.1 signatures with the Android 13+ upgrade lineage."
    inputs.file(assembledAndroidRelease)
    inputs.file(androidSigningLineage)
    outputs.file(androidLegacyUpgradeOutput)
    environment("JIEXI_NEW_STORE_PASS", releaseProperties.getProperty("storePassword", ""))
    environment("JIEXI_NEW_KEY_PASS", releaseProperties.getProperty("keyPassword", ""))
    doFirst {
        val output = androidLegacyUpgradeOutput
        androidReleaseOutputDirectory.mkdirs()
        if (output.exists()) check(output.delete()) {
            "Unable to replace Android legacy-upgrade APK: $output"
        }
        file("${output.absolutePath}.idsig").delete()
    }
    commandLine(
        apksignerExecutable.absolutePath,
        "sign",
        "--out", androidLegacyUpgradeOutput.absolutePath,
        "--v1-signing-enabled", "false",
        "--v2-signing-enabled", "false",
        "--v3-signing-enabled", "true",
        "--v4-signing-enabled", "false",
        // Android 9-12 sees the new release key directly.
        "--ks", releaseProperties.getProperty("storeFile", ""),
        "--ks-key-alias", releaseProperties.getProperty("keyAlias", ""),
        "--ks-pass", "env:JIEXI_NEW_STORE_PASS",
        "--key-pass", "env:JIEXI_NEW_KEY_PASS",
        // Android 13+ additionally receives proof that the legacy signer was
        // authorized to rotate to this same release key.
        "--signer-for-min-sdk-version", "33",
        "--ks", releaseProperties.getProperty("storeFile", ""),
        "--ks-key-alias", releaseProperties.getProperty("keyAlias", ""),
        "--ks-pass", "env:JIEXI_NEW_STORE_PASS",
        "--key-pass", "env:JIEXI_NEW_KEY_PASS",
        "--signer-lineage", androidSigningLineage.absolutePath,
        assembledAndroidRelease.get().asFile.absolutePath
    )
}

val packageAndroidRelease by tasks.registering(Exec::class) {
    dependsOn(tasks.named("assembleRelease"))
    group = "distribution"
    description = "Build the public Android 4.0 APK using only the private release key."
    inputs.file(assembledAndroidRelease)
    outputs.file(androidReleaseOutput)
    environment("JIEXI_NEW_STORE_PASS", releaseProperties.getProperty("storePassword", ""))
    environment("JIEXI_NEW_KEY_PASS", releaseProperties.getProperty("keyPassword", ""))
    doFirst {
        androidReleaseOutputDirectory.mkdirs()
        if (androidReleaseOutput.exists()) check(androidReleaseOutput.delete()) {
            "Unable to replace Android release APK: $androidReleaseOutput"
        }
        file("${androidReleaseOutput.absolutePath}.idsig").delete()
    }
    commandLine(
        apksignerExecutable.absolutePath,
        "sign",
        "--out", androidReleaseOutput.absolutePath,
        // Deliberately omit the legacy lineage: Android requires a v2 signer
        // to be the oldest lineage signer, which would reintroduce the debug
        // certificate on Android 7-12. The public APK is release-key-only.
        "--v1-signing-enabled", "false",
        "--v2-signing-enabled", "true",
        "--v3-signing-enabled", "true",
        "--v4-signing-enabled", "false",
        "--ks", releaseProperties.getProperty("storeFile", ""),
        "--ks-key-alias", releaseProperties.getProperty("keyAlias", ""),
        "--ks-pass", "env:JIEXI_NEW_STORE_PASS",
        "--key-pass", "env:JIEXI_NEW_KEY_PASS",
        assembledAndroidRelease.get().asFile.absolutePath
    )
}

tasks.register<Exec>("verifyAndroidRelease") {
    dependsOn(packageAndroidRelease)
    group = "verification"
    description = "Verify the public APK uses the release key on every supported API."
    commandLine(
        apksignerExecutable.absolutePath,
        "verify",
        "--verbose",
        "--print-certs",
        "--min-sdk-version", "24",
        androidReleaseOutput.absolutePath
    )
}

tasks.register<Exec>("verifyAndroidLegacyUpgrade") {
    dependsOn(packageAndroidLegacyUpgrade)
    group = "verification"
    description = "Verify the v3/v3.1-only Android 13+ legacy migration APK."
    commandLine(
        apksignerExecutable.absolutePath,
        "verify",
        "--verbose",
        "--print-certs",
        // The migration APK intentionally has no v1/v2 block and therefore
        // cannot be installed by Android 7-8 even though the manifest minSdk
        // remains 24. It is only distributed to detected Android 13+ clients.
        "--min-sdk-version", "28",
        androidLegacyUpgradeOutput.absolutePath
    )
}
